LF				equ	10
lf				equ	LF
CR				equ	13
cr				equ	CR
NULL			equ	0
null			equ	NULL
TRUE			equ	1
true			equ	TRUE
FALSE			equ	0
false			equ	FALSE
STDIN			equ 0
stdin			equ STDIN
STDOUT			equ 1
stdout			equ STDOUT
STDERR			equ 2
stderr			equ	STDERR
EXIT_SUCCESS	equ	0
EXIT_FAILURE	equ 1
